#!/bin/sh

# $Id$
# $URL$

# exit on errors
set -e

# set nicer prompt for tracing
PS4="$0:\$LINENO> "
set -x

# automake requires ChangeLog — point to CHANGELOG.md if it exists
[ ! -f ChangeLog ] && [ -f CHANGELOG.md ] && ln -s CHANGELOG.md ChangeLog

aclocal
libtoolize --copy --force 
autoheader
automake --add-missing --copy --foreign 
autoconf

